---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  install: {}
  interval: 30s
  targetNamespace: staging
  values:
    image:
      tag: 2.9.17
    ingress:
      host: staging.devops-toolkit.abce7e6c89d2a47f5b60d67269305f9a-eb96cf2c3d17820c.elb.us-west-2.amazonaws.com

